# Development Environment Configuration
spring:
  # Graceful shutdown configuration
  lifecycle:
    timeout-per-shutdown-phase: 45s

  datasource:
    url: jdbc:h2:mem:logistics;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    generate-unique-name: false
    # Enhanced connection validation and lifecycle management
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      initialization-fail-timeout: -1
      validate-on-migrate: true
      auto-commit: false
      pool-name: LogisticsHikariCP
      register-mbeans: true

  # FIXED JPA Development Settings - Removed invalid connection handling mode
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        jdbc:
          batch_size: 10
          fetch_size: 50
        order_inserts: true
        order_updates: true
        current_session_context_class: thread
        enable_lazy_load_no_trans: false
    defer-datasource-initialization: true
    open-in-view: false

  # H2 Console enabled for development
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  # DevTools Configuration - COMPLETELY DISABLED
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    add-properties: false

  # SQL Initialization
  sql:
    init:
      mode: always
      continue-on-error: false

  # Add task execution shutdown configuration
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30s
    scheduling:
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: 30s

# Development Logging
logging:
  level:
    com.logistics: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.context.support.DefaultLifecycleProcessor: DEBUG
    org.springframework.boot.web.embedded.tomcat.GracefulShutdown: DEBUG
    org.springframework.scheduling: DEBUG
    org.h2: WARN
    com.zaxxer.hikari: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# Development Server Configuration
server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 60000
    keep-alive-timeout: 30000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

# Development OpenAPI Configuration
springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: true
  api-docs:
    enabled: true

# Development-specific Application Configuration
app:
  logistics:
    ai-agent:
      processing-timeout: 60
      max-retry-attempts: 1
      notification-enabled: true
    warehouse:
      mock-data-enabled: true
      debug-instructions: true
    shipping:
      mock-delivery-enabled: true
      accelerated-processing: true
    notifications:
      console-output: true
      mock-external-services: true

# Development CORS Configuration
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: false

# Actuator - Full exposure in development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true